### ISSUE TITLE
Session is not set

### ISSUE THREAD

**Issue by sushant12** [leikir/devise-token-auth-omniauth-example#1]
Hi guys, It would be great if you would complete this example. I am stuck setting sessions after the user is logged in via the oauth. 

https://github.com/lynndylanhurley/devise_token_auth/issues/1007

**Comment by levraipixel** [comment]
@sushant12 Have you fixed it somewhere?

**Comment by sushant12** [comment]
@yhourdel I followed a different approach. I had a route that would return a oauth signup url then the frontend app would req that url to get that oauth url. After the user clicks in sign_in_with_google btn they will see the oauth page and after filling the info they will then be redirected to the frontend app 's home page with the google code which will then be send to the api server to get access token and all that . The api server will then make a req to google server for user profile. the profile is saved inthe db and a token is sent in the response to the frontend app.
 
```
       skip_after_action :update_auth_header, :only => [:token_for_code]
	def log_in_or_create_employee(user_info)
		@resource = Employee.find_by email: user_info["emails"][0]["value"]
		if @resource.nil?
			password = Devise.friendly_token[0,10]
			@resource = Employee.new({
				name: user_info["displayName"], 
				admin: true, 
				first_name: CustomRegex.japanese?(user_info["name"]["givenName"]) ? '' : user_info["name"]["givenName"],
				last_name: CustomRegex.japanese?(user_info["name"]["familyName"]) ? '' : user_info["name"]["familyName"],
				email: user_info["emails"][0]["value"],
				password: password,
				password_confirmation: password
				})
		end
			@client_id = SecureRandom.urlsafe_base64(nil, false)
      @token     = SecureRandom.urlsafe_base64(nil, false)
      @resource.tokens[@client_id] = {
              token: BCrypt::Password.create(@token),
              expiry: (Time.now + DeviseTokenAuth.token_lifespan).to_i
      }
      @resource.skip_confirmation!
			@resource.save!
			return render json: {client_id: @client_id, expiry: @resource.tokens[@client_id][:"expiry"],
													 token: @token, uid: @resource.uid
													}
	end
```

**Comment by levraipixel** [comment]
Ok thanks, that looks like a fine idea!
